/*
GitHub v3 REST API

GitHub's v3 REST API.

API version: 1.1.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package github

import (
	"encoding/json"
)

// MergeGroupChecksRequested struct for MergeGroupChecksRequested
type MergeGroupChecksRequested struct {
	Action string `json:"action"`
	Installation *SimpleInstallation `json:"installation,omitempty"`
	Organization *OrganizationSimple `json:"organization,omitempty"`
	Repository *Repository `json:"repository,omitempty"`
	Sender *SimpleUser `json:"sender,omitempty"`
	MergeGroup MergeGroupChecksRequestedMergeGroup `json:"merge_group"`
}

// NewMergeGroupChecksRequested instantiates a new MergeGroupChecksRequested object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMergeGroupChecksRequested(action string, mergeGroup MergeGroupChecksRequestedMergeGroup) *MergeGroupChecksRequested {
	this := MergeGroupChecksRequested{}
	this.Action = action
	this.MergeGroup = mergeGroup
	return &this
}

// NewMergeGroupChecksRequestedWithDefaults instantiates a new MergeGroupChecksRequested object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMergeGroupChecksRequestedWithDefaults() *MergeGroupChecksRequested {
	this := MergeGroupChecksRequested{}
	return &this
}

// GetAction returns the Action field value
func (o *MergeGroupChecksRequested) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *MergeGroupChecksRequested) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *MergeGroupChecksRequested) SetAction(v string) {
	o.Action = v
}

// GetInstallation returns the Installation field value if set, zero value otherwise.
func (o *MergeGroupChecksRequested) GetInstallation() SimpleInstallation {
	if o == nil || o.Installation == nil {
		var ret SimpleInstallation
		return ret
	}
	return *o.Installation
}

// GetInstallationOk returns a tuple with the Installation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergeGroupChecksRequested) GetInstallationOk() (*SimpleInstallation, bool) {
	if o == nil || o.Installation == nil {
		return nil, false
	}
	return o.Installation, true
}

// HasInstallation returns a boolean if a field has been set.
func (o *MergeGroupChecksRequested) HasInstallation() bool {
	if o != nil && o.Installation != nil {
		return true
	}

	return false
}

// SetInstallation gets a reference to the given SimpleInstallation and assigns it to the Installation field.
func (o *MergeGroupChecksRequested) SetInstallation(v SimpleInstallation) {
	o.Installation = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *MergeGroupChecksRequested) GetOrganization() OrganizationSimple {
	if o == nil || o.Organization == nil {
		var ret OrganizationSimple
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergeGroupChecksRequested) GetOrganizationOk() (*OrganizationSimple, bool) {
	if o == nil || o.Organization == nil {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *MergeGroupChecksRequested) HasOrganization() bool {
	if o != nil && o.Organization != nil {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given OrganizationSimple and assigns it to the Organization field.
func (o *MergeGroupChecksRequested) SetOrganization(v OrganizationSimple) {
	o.Organization = &v
}

// GetRepository returns the Repository field value if set, zero value otherwise.
func (o *MergeGroupChecksRequested) GetRepository() Repository {
	if o == nil || o.Repository == nil {
		var ret Repository
		return ret
	}
	return *o.Repository
}

// GetRepositoryOk returns a tuple with the Repository field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergeGroupChecksRequested) GetRepositoryOk() (*Repository, bool) {
	if o == nil || o.Repository == nil {
		return nil, false
	}
	return o.Repository, true
}

// HasRepository returns a boolean if a field has been set.
func (o *MergeGroupChecksRequested) HasRepository() bool {
	if o != nil && o.Repository != nil {
		return true
	}

	return false
}

// SetRepository gets a reference to the given Repository and assigns it to the Repository field.
func (o *MergeGroupChecksRequested) SetRepository(v Repository) {
	o.Repository = &v
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *MergeGroupChecksRequested) GetSender() SimpleUser {
	if o == nil || o.Sender == nil {
		var ret SimpleUser
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MergeGroupChecksRequested) GetSenderOk() (*SimpleUser, bool) {
	if o == nil || o.Sender == nil {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *MergeGroupChecksRequested) HasSender() bool {
	if o != nil && o.Sender != nil {
		return true
	}

	return false
}

// SetSender gets a reference to the given SimpleUser and assigns it to the Sender field.
func (o *MergeGroupChecksRequested) SetSender(v SimpleUser) {
	o.Sender = &v
}

// GetMergeGroup returns the MergeGroup field value
func (o *MergeGroupChecksRequested) GetMergeGroup() MergeGroupChecksRequestedMergeGroup {
	if o == nil {
		var ret MergeGroupChecksRequestedMergeGroup
		return ret
	}

	return o.MergeGroup
}

// GetMergeGroupOk returns a tuple with the MergeGroup field value
// and a boolean to check if the value has been set.
func (o *MergeGroupChecksRequested) GetMergeGroupOk() (*MergeGroupChecksRequestedMergeGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MergeGroup, true
}

// SetMergeGroup sets field value
func (o *MergeGroupChecksRequested) SetMergeGroup(v MergeGroupChecksRequestedMergeGroup) {
	o.MergeGroup = v
}

func (o MergeGroupChecksRequested) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["action"] = o.Action
	}
	if o.Installation != nil {
		toSerialize["installation"] = o.Installation
	}
	if o.Organization != nil {
		toSerialize["organization"] = o.Organization
	}
	if o.Repository != nil {
		toSerialize["repository"] = o.Repository
	}
	if o.Sender != nil {
		toSerialize["sender"] = o.Sender
	}
	if true {
		toSerialize["merge_group"] = o.MergeGroup
	}
	return json.Marshal(toSerialize)
}

type NullableMergeGroupChecksRequested struct {
	value *MergeGroupChecksRequested
	isSet bool
}

func (v NullableMergeGroupChecksRequested) Get() *MergeGroupChecksRequested {
	return v.value
}

func (v *NullableMergeGroupChecksRequested) Set(val *MergeGroupChecksRequested) {
	v.value = val
	v.isSet = true
}

func (v NullableMergeGroupChecksRequested) IsSet() bool {
	return v.isSet
}

func (v *NullableMergeGroupChecksRequested) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMergeGroupChecksRequested(val *MergeGroupChecksRequested) *NullableMergeGroupChecksRequested {
	return &NullableMergeGroupChecksRequested{value: val, isSet: true}
}

func (v NullableMergeGroupChecksRequested) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMergeGroupChecksRequested) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


